apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: movievault
data:
  POSTGRES_DB: movievault
  POSTGRES_USER: appuser
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: movievault
type: Opaque
stringData:
  POSTGRES_PASSWORD: "SuperSecret123!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: movievault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: movievault
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
