# ── Zookeeper ──────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: movievault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      tolerations:
        - key: "eks.amazonaws.com/compute-type"
          operator: "Equal"
          value: "auto"
          effect: "NoSchedule"
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: movievault
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
---
# ── Kafka ───────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: movievault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false # Disable downward API for cleaner environment variables
      tolerations:
        - key: "eks.amazonaws.com/compute-type"
          operator: "Equal"
          value: "auto"
          effect: "NoSchedule"
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.movievault.svc.cluster.local:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka.movievault.svc.cluster.local:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512m -Xms256m"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "1"
          ports:
            - containerPort: 9092
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: movievault
spec:
  selector:
    app: kafka
  ports:
    - port: 9092